const START_TYPING = 'START_TYPING';
const VERIFY_USER = 'VERIFY_USER';
const USER_CONNECTED = 'USER_CONNECTED';
const MESSAGE_SENT = 'MESSAGE_SENT';
const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';
const EVENT_CHAT = 'EVENT_CHAT';

module.exports = {
  START_TYPING,
  VERIFY_USER,
  USER_CONNECTED,
  MESSAGE_SENT,
  MESSAGE_RECIEVED,
  EVENT_CHAT
};
